"""field remind_time added

Revision ID: 1e03036843d4
Revises: 8edfe076ae60
Create Date: 2025-06-19 09:25:38.391485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e03036843d4'
down_revision: Union[str, None] = '8edfe076ae60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('remind_time', sa.Time(), server_default=sa.text("'08:00:00'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'remind_time')
    # ### end Alembic commands ###
