"""telegram_group_id column unique false

Revision ID: 2c7df68f203a
Revises: fecbc000e82f
Create Date: 2025-06-23 08:59:46.918215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c7df68f203a'
down_revision: Union[str, Sequence[str], None] = 'fecbc000e82f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('groups_telegram_group_id_key'), 'groups', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('groups_telegram_group_id_key'), 'groups', ['telegram_group_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
