"""chat_name column renamed to chat_type

Revision ID: 8993fb4585d2
Revises: 2c7df68f203a
Create Date: 2025-06-23 16:27:34.619755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8993fb4585d2'
down_revision: Union[str, Sequence[str], None] = '2c7df68f203a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('chat_type', sa.String(length=10), nullable=True))
    op.drop_column('events', 'chat_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('chat_name', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_column('events', 'chat_type')
    # ### end Alembic commands ###
