"""days of month column added

Revision ID: 95dc82568443
Revises: 8993fb4585d2
Create Date: 2025-06-25 13:14:01.524792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dc82568443'
down_revision: Union[str, Sequence[str], None] = '8993fb4585d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('days_of_month', sa.ARRAY(sa.Integer()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'days_of_month')
    # ### end Alembic commands ###
